# Homework 6. Real / Fake News Classification

**Due Date: Dec 4, 2025**

You’ve just joined UMD News as a data scientist, and the Fact-Checking Department is begging for help 🙏🙏🙏.

They've been working 24/7 trying to spot fake news, and let’s just say... morale is low and coffee supplies are dangerously high ☕⚠️.

They need you to **build a fake news classifier** to help catch false stories automatically—so they can finally take a break (or at least a nap)  🛌😴.

They’ve sent you a dataset to get started.

## TASK 1 [21 points total] Download, Assess, and Preprocess Data

### TASK 1.1 [0 points]: Download the data.
Put the two csv files into the same directory as `main.ipynb`. Here is a piece of code to check whether you did correctly.

In [33]:
import os
files = os.listdir('.')
print("real.csv is in the folder:", "real.csv" in files)
print("fake.csv is in the folder:", "fake.csv" in files)

real.csv is in the folder: True
fake.csv is in the folder: True

### TASK 1.2 [5 points]: Load the data and have a first glance.
Look at the dataset. In the box below, write a paragraph describing the dataset.

In [34]:
import pandas as pd
import numpy

fake_df = pd.read_csv("fake.csv")
real_df = pd.read_csv("real.csv")

display(fake_df.head())
display(real_df.head())

display(fake_df.shape)
display(real_df.shape)

real_df["subject"].value_counts()

,title,text,subject,date
0,EP #15: Patrick Henningsen LIVE – ‘Crisis of A...,Join Patrick every Wednesday at Independent T...,US_News,"March 2, 2017"
1,"Desperate For Members, White Supremacists Beg...","By now, everyone is aware of how Donald Trump ...",News,"August 10, 2017"
2,Black Caucus Demands Action: Calls On Congres...,"Following the horrific tragedy in Dallas, Texa...",News,"July 8, 2016"
3,MI SCHOOL SENDS Welcome Back Packet Warning Ki...,"ROSEVILLE, Mich. Parents are raging after a ...",left-news,"Aug 8, 2017"
4,WATCH HER SKI! AMERICAN TAXPAYERS ON THE HOOK ...,WOULDN T YOU LIKE TO KNOW THE GRAND TOTAL AND ...,Government News,"May 7, 2015"

,title,text,subject,date
0,"Thousands march in Helsinki in far-right, anti...",HELSINKI (Reuters) - Supporters of the far rig...,worldnews,"December 6, 2017"
1,Marseille attacker probably radicalized by bro...,ROME (Reuters) - The brother of the man who ki...,worldnews,"October 9, 2017"
2,"U.S. farmers slam Trump's Cuba clampdown, pres...",CHICAGO (Reuters) - U.S. farm groups criticize...,politicsNews,"June 16, 2017"
3,Turkey investigates reports that folk dancers ...,ANKARA (Reuters) - Turkey is investigating rep...,worldnews,"December 5, 2017"
4,Trump administration would ignore WTO rulings ...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"March 1, 2017"

(5000, 4)

(5000, 4)

subject
politicsNews    2638
worldnews       2358
                   4
Name: count, dtype: int64

Paragraph with answer here. One point each for:
- writing a paragraph
- the size of the dataset
- what each file represents
- what each column represents
- the datatype of each column

Each dataset has 5000 rows with 4 columns of data each. The real_df represents the DataFrame of the real.csv file, which contains real, actual reported news. The fake_df represents the Dataframe of the fake.csv file, which I assume is composed of fictitious and "fake" news stories. The "title" column is the story title, "text" is the story itself, "subject" is either politicsNews or worldnews value, and "date" is the date, in a Month/day/year order. All column data types are strings.

### TASK 1.3 [5 points] What do you think?
You get home from work and your friend asks you about your job. What do you think about training a classifier on this dataset?

Paragraph with answer here. We expect them to write how this is easy (all the true examples have cities associated with them) or hard (3 points), and the context of how this classifier may be used (2 points).

### TASK 1.4 [3 Points] Check for empty entries
Your colleague told you: "Hey, some entries may be empty." Is that true? Count the number of entries per column that don't have information in them.

In [35]:
def count_empty_entries(df):
    for column in df.columns:
        ### TODO Add Your Code Here: Count the number of empty entries in each column
            empty_count = (df[column] == " ").sum()
            print(f"Column '{column}' has {empty_count} empty entries.")

print("Counting empty entries in the real dataset:")
count_empty_entries(real_df)
print("\nCounting empty entries in the real dataset:")
count_empty_entries(fake_df)

Counting empty entries in the real dataset:
Column 'title' has 6 empty entries.
Column 'text' has 6 empty entries.
Column 'subject' has 4 empty entries.
Column 'date' has 5 empty entries.

Counting empty entries in the real dataset:
Column 'title' has 5 empty entries.
Column 'text' has 142 empty entries.
Column 'subject' has 5 empty entries.
Column 'date' has 10 empty entries.

### TASK 1.5 [(1+2) Points] Delete some columns and rows.
After discussing with your team leader, you both believe **`subject` and `date` are not useful for your analysis**, so you decide to **drop them** from both datasets.

In addition, you will **remove any rows that have empty entries in the `title` or `text` column** from both datasets.

In [36]:
# 1 point
def remove_subject_and_date(df: pd.DataFrame):
    # TODO Add your code here: drop the 'subject' and 'date' columns from the dataframe
    df.drop(["subject", "date"], axis=1, inplace=True)
    return df

real_df = remove_subject_and_date(real_df)
fake_df = remove_subject_and_date(fake_df)
print("real_df's current columns:,", real_df.columns)
print("fake_df's current columns:,", fake_df.columns)

real_df's current columns:, Index(['title', 'text'], dtype='object')
fake_df's current columns:, Index(['title', 'text'], dtype='object')

In [ ]:
# 2 points
def remove_rows_with_empty_entries(df):
    # TODO Add your code here: remove rows with any empty entries in the dataframe
    df.dropna()
    return df

real_df = remove_rows_with_empty_entries(real_df)
fake_df = remove_rows_with_empty_entries(fake_df)
print("After removing rows with empty entries:")
print("Real dataset shape after cleaning:", real_df.shape)
print("Fake dataset shape after cleaning:", fake_df.shape)

After removing rows with empty entries:
Real dataset shape after cleaning: (5000, 2)
Fake dataset shape after cleaning: (5000, 2)

### TASK 1.6 [5 Points] Remove special characters.
You may notice there are many special characters in the text data, such as punctuation marks, numbers, and other non-alphabetic characters.

Please **remove all these special characters** from the text data in both datasets. **Only keep alphabetic characters and spaces.**

In addition, **make all the characters lower-case**.

In [38]:
def remove_special_characters(df):
    # TODO Add your code here: remove special characters from both columns.

    return df

real_df = remove_special_characters(real_df)
fake_df = remove_special_characters(fake_df)
print("After removing special characters:")
print("Real dataset shape after cleaning:", real_df.head(3))
print("\n\nFake dataset shape after cleaning:", fake_df.head(3))

After removing special characters:
Real dataset shape after cleaning:                                                title  \
0  Thousands march in Helsinki in far-right, anti...
1  Marseille attacker probably radicalized by bro...
2  U.S. farmers slam Trump's Cuba clampdown, pres...

                                                text
0  HELSINKI (Reuters) - Supporters of the far rig...
1  ROME (Reuters) - The brother of the man who ki...
2  CHICAGO (Reuters) - U.S. farm groups criticize...


Fake dataset shape after cleaning:                                                title  \
0  EP #15: Patrick Henningsen LIVE – ‘Crisis of A...
1   Desperate For Members, White Supremacists Beg...
2   Black Caucus Demands Action: Calls On Congres...

                                                text
0   Join Patrick every Wednesday at Independent T...
1  By now, everyone is aware of how Donald Trump ...
2  Following the horrific tragedy in Dallas, Texa...

## TASK 2 [6 points total]. Create the training and testing test.

Now we have finished pre-processing the data. We are now constructing a training set and a testing set to build up and evaluate our classifier.

We will follow the steps:
1. TASK 1.1. Assign labels to each row.
2. TASK 1.2. Concatenate the two tables `real_df` and `fake_df` into one data frame `union_df`.
3. TASK 1.3. Split the `union_df` into `train_df` and `test_df`, where the training/testing set contains 80%/20% of the data.

### TASK 2.1 [2 Points]. Assign labels to each row.
Add a `label` column to each of the data frame. For `real_df`, the `label` column is all 1. For `fake_df`, the `label` column is all 0.

In [39]:
def add_label_column(df, value):
    # TODO Add your code here: add a new column 'label' to the dataframe with the specified value

    return df

real_df = add_label_column(real_df, 1)  # Label for real emails
fake_df = add_label_column(fake_df, 0)  # Label for fake emails
print("After adding label column:")
print("Real dataset shape with labels:", real_df.head(3))
print("\n\nFake dataset shape with labels:", fake_df.head(3))

After adding label column:
Real dataset shape with labels:                                                title  \
0  Thousands march in Helsinki in far-right, anti...
1  Marseille attacker probably radicalized by bro...
2  U.S. farmers slam Trump's Cuba clampdown, pres...

                                                text
0  HELSINKI (Reuters) - Supporters of the far rig...
1  ROME (Reuters) - The brother of the man who ki...
2  CHICAGO (Reuters) - U.S. farm groups criticize...


Fake dataset shape with labels:                                                title  \
0  EP #15: Patrick Henningsen LIVE – ‘Crisis of A...
1   Desperate For Members, White Supremacists Beg...
2   Black Caucus Demands Action: Calls On Congres...

                                                text
0   Join Patrick every Wednesday at Independent T...
1  By now, everyone is aware of how Donald Trump ...
2  Following the horrific tragedy in Dallas, Texa...

### TASK 2.2 [2 Points]. Concatenate the two data frames into one.

In [40]:
def concatenate_dataframes(df1, df2):
    # TODO Add your code here: concatenate the two dataframes

    return combined_df

union_df = concatenate_dataframes(real_df, fake_df)
print("Combined dataset shape:", union_df.shape)
print("First 3 rows of the combined dataset:")
print(union_df.head(3))
print("\n\nLast 3 rows of the combined dataset:")
print(union_df.tail(3))

NameError: name 'combined_df' is not defined

### TASK 2.3 [2 Points]. Split the dataset into training and testing sets.

There are many ways to implement this. You could either implement the splitting from scratch, or you could use proper functions in `sklearn.model_selection`.

The printed results don't need to be exactly the same as the expected output, but they should be close.

In [ ]:
def split_dataset(df, train_size=0.8):
    # TODO Add your code here: split the dataset into training and testing sets

    return train_df, test_df

train_df, test_df = split_dataset(union_df, train_size=0.8)
print("Training dataset shape:", train_df.shape)
print("Testing dataset shape:", test_df.shape)
print("Proportion of training set:", len(train_df) / len(union_df))
print("Proportion of testing set:", len(test_df) / len(union_df))
print("#Positive samples in training set:", len(train_df[train_df['label'] == 1]))
print("#Negative samples in training set:", len(train_df[train_df['label'] == 0]))
print("#Positive samples in testing set:", len(test_df[test_df['label'] == 1]))
print("#Negative samples in testing set:", len(test_df[test_df['label'] == 0]))

## TASK 3 [29 points total]: Build a classifier and evaluate its performance.
Now we have our training set and testing set ready. We are going to train classifiers and evaluate its performance.

After discussing with your team leader,
* You are going to first encode the news, which means convert each piece of news into a fixed-length vector. And then you will train a classifier.
* You are going to try two encoders, `TfidfVectorizer` and `SentenceTransformer`. You will use both `Linear SVM` and `Logistic Regression` as the classifier.
* Regarding the inputs to the classifiers, you are unsure **whether `title` or `text` will give better prediction.** So you will try both for each way of classification.

So you plan the following combinations of experiments. The target of this task is to fill in the **classification accuracy on the test set** into the table at the end.
|  | TfidfVectorizer | SentenceTransformer |
|----------|----------|----------|
| title |  |  |
| text |  |  |

### TASK 3.1: TfidfVectorizer - Linear SVM

#### TASK 3.1.1 [5 Points]: TfidfVectorizer
Currently, our input is a string. Machine learning models like Linear SVM cannot receive strings as inputs. Therefore, our first step is to convert the input strings into feature vectors. We will use `TfidfVectorizer` from `sklearn.feature_extraction.text` to achieve this. You are recommended to read the documentation to facilitate your coding.

You would do the following:
1. Fit the `TfidfVectorizer` using the training inputs.
2. Use the fitted vectorizer to transform the testing inputs.
3. Do the above steps for both `title` column and `text` column.

Hint: When fitting the `TfidfVectorizer`, pay attention to the `max_features` parameter. If you find the training later on takes a very long time, consider setting an appropriate value for this parameter.

In [ ]:
def extract_feature_vectors(train_df_input_column, test_df_input_column):
    # TODO Add your code here: first fit the TfidfVectorizer on the training set, then transform both the training and testing sets using the fitted vectorizer.

    return train_feature_vectors, test_feature_vectors

train_title_feature_vectors, test_title_feature_vectors = extract_feature_vectors(train_df['title'], test_df['title'])
train_text_feature_vectors,  test_text_feature_vectors  = extract_feature_vectors(train_df['text'],  test_df['text'])
print("Feature vectors for training set (title):", train_title_feature_vectors.shape)
print("Feature vectors for testing set (title): ", test_title_feature_vectors.shape)
print("Feature vectors for training set (text): ", train_text_feature_vectors.shape)
print("Feature vectors for testing set (text):  ", test_text_feature_vectors.shape)

### TASK 3.1.2 [8 Points]: Linear SVM.
Train a **Linear SVM model** on the training set and evaluate its performance on the testing set. Feel free to set your own hyper-parameters.

Consider using `accuracy_score` and `classification_report` from `sklearn.metrics` to evaluate and present your results.

You don't need to match the exact values from `expected_output.ipynb`, but you shall obtain a similar format of outputs and reasonable values (e.g. accuracy not lower than 0.85).

In [ ]:
def trainSVM(train_feature_vectors, train_labels, test_feature_vectors, test_labels):
    # TODO Add your code here: train a Linear SVM model using the training feature vectors and labels, then evaluate the model on the testing set.
    from sklearn.svm import LinearSVC
    from sklearn.metrics import accuracy_score, classification_report

    # Create and train the model


    # Make predictions on the test set


    # Evaluate the model


    print("Accuracy of Linear SVM Model:", accuracy)
    print("Classification Report:\n", report)
    return model, accuracy, report

# Prepare labels for training and testing
train_labels = train_df['label'].values
test_labels = test_df['label'].values
# Train and evaluate the Linear SVM model using title feature vectors
model_title, accuracy_title, report_title = trainSVM(
    train_title_feature_vectors, train_labels,
    test_title_feature_vectors, test_labels
)
# Train and evaluate the Logistic Regression model using text feature vectors
model_text, accuracy_text, report_text = trainSVM(
    train_text_feature_vectors, train_labels,
    test_text_feature_vectors, test_labels
)
# Print the accuracies for both models
print("Accuracy of Linear SVM Model using title feature vectors:", accuracy_title)
print("Accuracy of Linear SVM Model using text feature vectors:", accuracy_text)

### TASK 3.2 SentenceTransformer - Logistic Regression
You will use a python package named `sentence_transformers` to convert a sentence into a 384-dimensional vector. You are encouraged to read through the documentation: [https://sbert.net/](https://sbert.net/), which describes its simple interface.

Similar to the previous task, you will first transform the title/text into vectors and train a logistic regression to classify the news.

#### TASK 3.2.1 [3 Points] Install Sentence Transformer.
First you will install the sentence-transformers pakcage using pip. `pip install -U sentence-transformers` After installation, you can test-run the following codes from [https://sbert.net/](https://sbert.net/) to see whether it is successfully installed.

In [ ]:
from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("paraphrase-MiniLM-L3-v2")

# The sentences to encode
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sentences)
print(embeddings.shape)
# [3, 384]

# 3. Calculate the embedding similarities
similarities = model.similarity(embeddings, embeddings)
print(similarities)
# tensor([[1.0000, 0.6660, 0.1046],
#         [0.6660, 1.0000, 0.1411],
#         [0.1046, 0.1411, 1.0000]])

#### TASK 3.2.2 [5 Points] Transform title/text into vectors using SentenceTransformer
**Warning: This may take longer than expected to run. Try not to rerun it everytime you refresh. We suggest that once you complete this task, create a variable to save the result.**

In [ ]:
def transform_into_vectors(train_df_input_column, test_df_input_column):
    # TODO Add your code here: first fit the SentenceTransformer on the training set, then transform both the training and testing sets using the fitted vectorizer.

    return train_feature_vectors, test_feature_vectors

train_title_feature_vectors, test_title_feature_vectors = transform_into_vectors(train_df['title'], test_df['title'])
print("Feature vectors for training set (title):", train_title_feature_vectors.shape)
print("Feature vectors for testing set (title): ", test_title_feature_vectors.shape)
train_text_feature_vectors,  test_text_feature_vectors  = transform_into_vectors(train_df['text'],  test_df['text'])
print("Feature vectors for training set (text): ", train_text_feature_vectors.shape)
print("Feature vectors for testing set (text):  ", test_text_feature_vectors.shape)

### TASK 3.2.3 [3 Points]: Logistic Regression (You can reuse majority of the code from TASK 3.1.2, see how robust the package is designed)
Train a **Logistic Regression model** on the training set and evaluate its performance on the testing set. Feel free to set your own hyper-parameters.

Consider using `accuracy_score` and `classification_report` from `sklearn.metrics` to evaluate and present your results.

You don't need to match the exact values from `expected_output.ipynb`, but you shall obtain a similar format of outputs and reasonable values (e.g. accuracy not lower than 0.85).

In [ ]:
def trainLogisticRegression(train_feature_vectors, train_labels, test_feature_vectors, test_labels):
    # TODO Add your code here: train a Logistic Regression model using the training feature vectors and labels, then evaluate the model on the testing set.
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import accuracy_score, classification_report

    # Create and train the model


    # Make predictions on the test set


    # Evaluate the model


    print("Accuracy of Logistic Regression Model:", accuracy)
    print("Classification Report:\n", report)
    return model, accuracy, report

# Prepare labels for training and testing
train_labels = train_df['label'].values
test_labels = test_df['label'].values
# Train and evaluate the Logistic Regression model using title feature vectors
model_title, accuracy_title, report_title = trainLogisticRegression(
    train_title_feature_vectors, train_labels,
    test_title_feature_vectors, test_labels
)
# Train and evaluate the Logistic Regression model using text feature vectors
model_text, accuracy_text, report_text = trainLogisticRegression(
    train_text_feature_vectors, train_labels,
    test_text_feature_vectors, test_labels
)
# Print the accuracies for both models
print("Accuracy of Logistic Regression Model using title feature vectors:", accuracy_title)
print("Accuracy of Logistic Regression Model using text feature vectors:", accuracy_text)

### TASK 3.3 [5 Points]: Report to your team leader.

Finally, fill in the accuracy into the table according to your experiments.

|  | TfIdfVectorizer | SentenceTransformer |
|----------|----------|----------|
| title | ??? | ??? |
| text  | ??? | ??? |

Send your team leader a message : "Hi manager, I recommend to use **[???]** as inputs, and use **[???]** as the input encoder. This will give us an accuracy of **[???]**."

Two minutes later, your team leader replies:

"Wonderful job!!! I will promote you as the senior data scientist next year!"

### TASK 4: Convolutional Neural Networks (15 points)

For this last bonus section, you will implement and train a convolutional neural network for the classification task on the CIFAR10 image dataset. (You can refer to this page for these questions: https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)

##### 4.1. Preparation of Data Loaders (5 pts)

**TASK**: Prepare **train_loader** and **test_loader**.

**Requirements**:
- Set the **batch size** to **4** for both loaders.
- Ensure that **train_loader** samples the dataset randomly (refer to the **shuffle** argument in DataLoader).

In [ ]:
### DO NOT MODIFY HERE!
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, TensorDataset

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import matplotlib.pyplot as plt
import numpy as np

# functions to show an image
def imshow(img):
    img = img / 2 + 0.5
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()

# Load the data
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
test_dataset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)

classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

In [ ]:
### YOUR ANSWER HERE
batch_size =
train_loader =
test_loader =

batch_size = train_loader.batch_size
num_train_data = len(train_loader) * batch_size
num_test_data = len(test_loader) * batch_size
feat_dim = train_loader.dataset[0][0].shape[0]
image_size = train_loader.dataset[0][0].shape[1:]

In [ ]:
### DO NOT MODIFY HERE!
try:
    assert(type(train_loader) == DataLoader)
    assert(type(test_loader) == DataLoader)
except:
    print('"train_loader" and "test_loader" must be DataLoader type!')

print("Batch Size:", batch_size)
print("Number of Train Data:", num_train_data)
print("Number of Test Data:", num_test_data)
print("Feature Dimension:", feat_dim)
print("Image Size:", image_size)

In [ ]:
### DO NOT MODIFY HERE!
# get some random training images
data_iter = iter(train_loader)
data, targets = next(data_iter)

# show images
imshow(torchvision.utils.make_grid(data))
# print labels
print(' '.join(f'{classes[targets[j]]:5s}' for j in range(batch_size)))

##### 4.2. Define Convolutional Neural Netwtork (5 pts)

**TASK**: Implement the **ConvNetModel** and instantiate
 the **model** variable.

**Requirements**:
- The model should include **Conv2d**, **MaxPool2D**, and **Linear** layers. For example, you can define layers such as conv1, pool, conv2, fc1, fc2, and fc3, with ReLU activations between them.
- The final output of the network should come directly from a **Linear** layer without an activation function.

In [ ]:
### YOUR ANSWER HERE

class ConvNetModel(nn.Module):
    def __init__(self):
        super().__init__()


    def forward(self, x):
        return x

model = ConvNetModel()

In [ ]:
### DO NOT MODIFY HERE!
try:
    assert(type(model) == ConvNetModel)
except:
    print('"model" must be ConvNetModel type!')

num_layers = len(list(model.children()))
input_ch = list(model.children())[0].in_channels
output_dim = list(model.children())[-1].out_features

print("Number of Layers:", num_layers)
print("Input Channels:", input_ch)
print("Output Dimension:", output_dim)

##### 4.3. Implement the ConvNet Training Loop (5 pts)

**TASK**: Implement the training loop with adequate loss function and optimizer.

**Requirements**:
- Use the **SGD** optimizer and the **CrossEntropyLoss** function.
- Your training training loop should implement both the forward pass (calculating losses) and the backward pass(zeroing the gradient and updating the parameters from the loss gradients)

In [ ]:
### YOUR ANSWER HERE
criterion =
optimizer =

epochs = 2
for epoch in range(epochs):  # loop over the dataset multiple times
    running_loss = 0.0
    for batch_idx, (data, targets) in enumerate(train_loader, 0):
        ### YOUR ANSWER HERE
        # Forward pass


        # Backward pass and optimize


        # print statistics
        running_loss += loss.item()
        if batch_idx % 2000 == 1999:    # print every 2000 mini-batches
            print(f'[{epoch + 1}, {batch_idx + 1:5d}] loss: {running_loss / 2000:.3f}')
            running_loss = 0.0

print('Finished Training')

In [ ]:
### DO NOT MODIFY HERE!
data_iter = iter(test_loader)
data, targets = next(data_iter)

outputs = model(data).softmax(dim=1).max(dim=1).indices

# print images
imshow(torchvision.utils.make_grid(data))

print('GroundTruth: ', ' '.join(f'{classes[targets[j]]:5s}' for j in range(4)))
print('Prediction: ', ' '.join(f'{classes[outputs[j]]:5s}' for j in range(4)))